service: pmapp-laravel-api

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  architecture: x86_64
  environment:
    # Laravel
    APP_ENV: production
    LOG_CHANNEL: stderr
    LOG_LEVEL: info

    # Supabase
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_ANON_KEY: ${env:SUPABASE_ANON_KEY}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}

    # DB (PostgreSQL)
    DB_CONNECTION: pgsql
    DB_HOST: ${env:DB_HOST}
    DB_PORT: 5432
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}

    # セッション/キャッシュ（Lambda用）
    CACHE_DRIVER: array
    SESSION_DRIVER: array
    FILESYSTEM_DRIVER: s3

    # AWS
    AWS_BUCKET: ${self:service}-${self:provider.stage}-storage

    # Bref
    BREF_BINARY_RESPONSES: 1

functions:
  # Web (FPM)
  web:
    handler: public/index.php
    runtime: php-82-fpm
    timeout: 28
    layers:
      # ランタイムのlayerは不要。pdo_pgsqlだけを追加
      - ${bref-extra:pgsql-php-82}
    events:
      - httpApi: '*'
    environment:
      APP_KEY: ${env:APP_KEY}
      APP_URL: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'

  # Artisan (CLI)
  artisan:
    handler: artisan
    runtime: php-82
    timeout: 120
    layers:
      - ${bref:layer.console}
      - ${bref-extra:pgsql-php-82}
    environment:
      APP_KEY: ${env:APP_KEY}

resources:
  Resources:
    StorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.AWS_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

plugins:
  - ./vendor/bref/bref
  - ./vendor/bref/extra-php-extensions

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!storage/logs/**'
    - '!.env*'
    - '!docker/**'
    - '!docker-compose.yml'
    - '!Dockerfile'
    - '!*.md'
    - '!phpcs.xml'
    - '!phpstan.neon'
    - '!phpunit.xml'
