name: PHP CodeSniffer

on: [pull_request]

jobs:
  phpcs:
    name: Code Style Check (PSR-12)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo
        tools: cs2pr

    - name: Setup ReviewDog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-8.2-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-8.2-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHP CodeSniffer with ReviewDog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php -d error_reporting="E_ERROR | E_WARNING | E_PARSE" vendor/bin/phpcs --report=checkstyle -q > phpcs-report.xml || true
        if [ -s phpcs-report.xml ]; then
          reviewdog -f=checkstyle -name="PHPCS" -reporter=github-pr-check -level=error < phpcs-report.xml
        else
          echo "No PHPCS issues found"
        fi

    - name: Run PHP CodeSniffer (fallback)
      if: failure()
      run: |
        php -d error_reporting="E_ERROR | E_WARNING | E_PARSE" vendor/bin/phpcs --report=checkstyle -q > phpcs-report.xml
        cs2pr phpcs-report.xml

    - name: Annotate results
      if: failure()
      run: |
        echo "::warning::PHP CodeSniffer found issues. Please run 'composer run phpcs-fix' to auto-fix issues."
